### ISSUE TITLE
torchaudio0.2 error

### ISSUE THREAD

**Issue by chsy1996** [atsiami/STAViS#1]
Hello, I run this line "pip install -r requirements.txt --user", but it show this error:
'''
ERROR: Could not find a version that satisfies the requirement torchaudio==0.2 (from -r requirements.txt (line 8)) (from versions: 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.5.1)
ERROR: No matching distribution found for torchaudio==0.2 (from -r requirements.txt (line 8))
'''
how can i install torchaudio 0.2 version, is it exists?

**Comment by chsy1996** [comment]
I have solved this problem by run "pip install http://download.pytorch.org/whl/torchaudio-0.2-cp35-cp35m-linux_x86_64.whl"

**Comment by atsiami** [comment]
It should work with a higher version too. 
requirements.txt needs an update.
Thanks for your comment!

**Comment by chsy1996** [comment]
> It should work with a higher version too.
> requirements.txt needs an update.
> Thanks for your comment!

Can you update this requirements.txt file?  Thx
I meet another problem, maybe cause by torchaudio too
This:
```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from dataset import get_training_set, get_validation_set, get_test_set
  File "/home/chsy1996/Downloads/dlproject/SaliencyEstimate/STAViS/dataset.py", line 1, in <module>
    from datasets.saliency_db import saliency_db
  File "/home/chsy1996/Downloads/dlproject/SaliencyEstimate/STAViS/datasets/saliency_db.py", line 10, in <module>
    import torchaudio
  File "/home/chsy1996/miniconda3/envs/saliencyestimation/lib/python3.5/site-packages/torchaudio/__init__.py", line 5, in <module>
    import _torch_sox
ImportError: /home/chsy1996/miniconda3/envs/saliencyestimation/lib/python3.5/site-packages/_torch_sox.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_4E
```

**Comment by chsy1996** [comment]
OK，I change to torch==1.4.0 and torchaudio==0.4, it works, Thx!

**Comment by pkoutras** [comment]
The requirements.txt has been updated. Thanks for pointing this issue.

**Comment by chsy1996** [comment]
> The requirements.txt has been updated. Thanks for pointing this issue.

Thank you very much!
