### ISSUE TITLE
Finetune the trained STAViS audiovisual models

### ISSUE THREAD

**Issue by yujinghu2000** [atsiami/STAViS#17]
I'd like to finetune your trained STAViS audiovisual models with my own dataset, so I add "--resume_path ./pretrained_models/stavis_audiovisual/audiovisual_split1_save_60.pth" to the training command. 
When I run:
```
python3 main.py  --batch_size 32 --n_threads 3 \
    --audiovisual --checkpoint 5 --n_epochs 80 \
    --result_path ./outputs/ft_test/ \
    --pretrain_path ./pretrained_models/stavis_visual_only/visual_split1_save_60.pth  \
    --audio_pretrain_path ./pretrained_models/soundnet8.pth \
    --resume_path ./pretrained_models/stavis_audiovisual/audiovisual_split1_save_60.pth \
    --video_list_train ./train_list_1.txt \
    --video_list_test ./test_list_1.txt
```
It shows:
```
Exception has occurred: RuntimeError
output with shape [64, 64, 1, 1] doesn't match the broadcast shape [64, 64, 128, 512]
  File "/VRSaliency/Finetunes/STAViS/STAViS-master/train.py", line 114, in train_epoch
    optimizer['fusion'].step()
  File "/VRSaliency/Finetunes/STAViS/STAViS-master/main.py", line 193, in <module>
    opt = train_epoch(i, opt.n_epochs, train_loader, model, optimizer, opt,
RuntimeError: output with shape [64, 64, 1, 1] doesn't match the broadcast shape [64, 64, 128, 512]

```
If I remove "--resume_path ./pretrained_models/stavis_audiovisual/audiovisual_split1_save_60.pth" , which means training from pretrained model, everything is ok.
Would you please tell me how to solve this problem and finetune your trained STAViS audiovisual models?

**Comment by pkoutras** [comment]
Thanks for raising this. It seems that the optimizer-state is not saved properly in the checkpoint. We updated the code with the `--skip_optimizer` option that skips the optimizer-state to be loaded.  It is better not loading the optimizer-state in the case of model-finetuning. The optimizer-state is useful when we resume a current experiment from a previous checkpoint from more epochs.
