### ISSUE TITLE
Not able to reach the dataset

### ISSUE THREAD

**Issue by ly-zhu** [atsiami/STAViS#3]
Hi, thanks for sharing the promising work. 
Seems the link of "http://cvsp.cs.ntua.gr/research/stavis/data" is not reachable currently.

**Comment by atsiami** [comment]
Hi, thank you for your interest on our work!
We currently have a connection issue on the server side and we are trying to fix it.
We will let you know when it is fixed, otherwise we will send a new link.

Sorry for the inconvenience

**Comment by atsiami** [comment]
Hi, the server for the data and the models is now up and running.
Sorry for the delay!

**Comment by ly-zhu** [comment]
Thanks!
