### ISSUE TITLE
file list

### ISSUE THREAD

**Issue by ly-zhu** [atsiami/STAViS#7]
Hi,

Is the annotation path of "--annotation_path_etmd_test ./data/fold_lists/ETMDa_av_list_test_${split}_fps.txt \" in all the "run_all_splits....sh" correct? Should the "ETMDa" be "ETMD"?

**Comment by atsiami** [comment]
It is correct. I mean, it corresponds to an actual file list for ETMD database. I understand that it might be confusing, but it is just the name of the file.

**Comment by atsiami** [comment]
I am sorry, you are absolutely right!
I fixed this. Thanks for pointing it out
