### ISSUE TITLE
DIEM_list_....txt file has no splits

### ISSUE THREAD

**Issue by ly-zhu** [atsiami/STAViS#8]
Hi,

(1)I'm very confused with the dataset DIEM, which has only the "DIEM_list_train_fps.txt" and "DIEM_list_test_fps.txt" (not having all the 3 splits, for example, the "AVAD_list_test_1_fps.txt",  "AVAD_list_test_2_fps.txt", and "AVAD_list_test_3_fps.txt").

(2) In all the "run_all_splits_....sh ", there are no annotation_path for the DIEM dataset, did you train and evaluate the model on DIEM dataset?
(3) I run the "run_all_splits_audiovisual_test.sh" with the provided pertained models, and got the diem saliency mask in 3 splits under the folder "experiments/audiovisual_test/split1_results/diem/", ".../.../split2_results/diem/", and ".../.../split3_results/diem/". However, the DIEM dataset has no split file list as shown in (1). 
(4) run the "compute_all_databases.sh", always got stuck at the evaluation on diem dataset, the following error 

     > In eval_diem (line 14) 
     Index exceeds matrix dimensions.

    Error in eval_diem (line 31)
    file_list = dir([test_data(i).pred_path '/*jpg']);

I'm not sure if the problem is because of the inconsistency of the DIEM file list.

**Comment by atsiami** [comment]
Hi,

DIEM dataset, contrary to all other datasets, has a standard split for development and test data, which has been widely adopted in the literature. That is why there are not 3 files for splits as in the other datasets. We explain this also on the paper. (For the other datasets, there was no standard split set, thus we had to do some cross-validation, so we split the dataset in 3 different splits.)

For the 3 different splits that the model was trained and tested, the same DIEM data have been used, concerning train and test data. Which means that for example in split3, DIEM data are the same data that were used in split1 and split2. On the contrary, all other datasets, have different videos in each split. 

Regarding the results, the model is trained and tested with data from all datasets. So, for each split, the results change, as it has been trained in different data. That is why model produces results for DIEM for all 3 splits.

I hope it is clear now!

**Comment by ly-zhu** [comment]
Thanks for your explanation! 
Following the instruction, I got the produced saliency maps by "bash run_all_splits_audiovisual_test.sh".
But I'm not able to pass the evaluation part (sh compute_all_databases.sh /home/test/STAViS experiments/audiovisual_train_test/),  had the above mentioned errors.  Could you reimplement this part and see if can encounter the same problem? Or any suggestions for possible reasons? Thanks!

**Comment by atsiami** [comment]
Hi,
You are right, there was a small bug in the eval code for DIEM database, which I think now is solved!
If you get the latest version, there is a fix!
I hope everything is OK now.

**Comment by ly-zhu** [comment]
With the fix, the problem of DIEM dataset is fixed. 
But had similar problem on the coutrot2 dataset.

    In eval_coutrot2 (line 14) 
    Index exceeds matrix dimensions.

    Error in eval_coutrot2 (line 31)
    file_list = dir([test_data(i).pred_path '/*jpg']);

**Comment by pkoutras** [comment]
Hi, there was one more bug fixed last night! Try to update to the latest commit and run again the compute_all_databases.sh (you could comment lines 18-23 if one dataset has finished).

**Comment by ly-zhu** [comment]
The problem still exists for dataset coutrot2.

**Comment by pkoutras** [comment]
We have replicated the whole evaluation code in a new machine and we have not any issues. 
Have you produced all the saliency maps? 
Have you run: 
[https://github.com/atsiami/STAViS/blob/f26599d8d7fcfa04c612e36c4173c6bd73744ede/compute_all_databases.sh#L16](https://github.com/atsiami/STAViS/blob/f26599d8d7fcfa04c612e36c4173c6bd73744ede/compute_all_databases.sh#L16)
to recreate the evaluation scripts per each database?

**Comment by ly-zhu** [comment]
Hi, recreating the evaluation scripts solved the problem. Thanks!
