### ISSUE TITLE
versions of pytorch and torchaudio

### ISSUE THREAD

**Issue by xuanhanyu** [atsiami/STAViS#9]
What are the versions of pytorch and torchaudio that used in your computer, when you run this program

**Comment by xuanhanyu** [comment]
when  loss_all_rest.backward(), the following error message appears:

one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 128, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)

The version of pytorch is 1.5.1 and torchaudio is 0.5.1

**Comment by pkoutras** [comment]
Thanks for pointing this!
The latest versions that we had tested were: pytorch==1.4.0 and torchaudio==0.4. The requirements.txt file has been updated. More probably something has changed in pytorch==1.5. If you can run it with latest versions please ping us to update the requirements.
